### PR TITLE
Update guzzlehttp Composer dependency to ^7.0

### PR DESCRIPTION
**Pull request by ctroms**
## Summary

This PR updates the `guzzlehttp/guzzle` composer dependency to `"^7.0"`

## Included in this PR

* Updated `guzzlehttp/guzzle` version  in `composer.json`

### CODE REVIEW

**Comment by dog5tar** [comment]
Exactly what I need too, that needs to go in.

**Comment by fffaraz** [comment]
8 months have passed and this PR is still ignored...
@finnhubio @dominhtri1995 care to take a look? I can't install it in a Laravel 8 project because of this.

**Comment by valtzu** [comment]
Maybe better would be `^6.2 || ^7.0` to not to break BC with older PHP versions. Guzzle 6 has `"php": ">=5.5"` while Guzzle 7 has `"php": "^7.2.5"`.

**Comment by dorqa95** [comment]
@dominhtri1995 could you please upgrade the guzzle package?

**Pull request closed without merging**
